// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmithBot.Database;

namespace SmithBot.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SmithBot.Models.BotUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activated")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferalUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReferrerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Subscriber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wallet")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("ReferrerUserId");

                    b.ToTable("BotUsers");
                });

            modelBuilder.Entity("SmithBot.Models.NewNFT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Number")
                        .HasColumnType("REAL");

                    b.Property<long>("OwnerTelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerWallet")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NFTs");
                });

            modelBuilder.Entity("SmithBot.Models.BotUser", b =>
                {
                    b.HasOne("SmithBot.Models.BotUser", "Referrer")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferrerUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
